create table if not exists public.prospects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  industry text,
  city text,
  province text,
  address text,
  phone text,
  whatsapp text,
  email text,
  instagram text,
  facebook text,
  website boolean default false,
  web_status text,
  priority text default 'Media',
  status text default 'Pendiente',
  next_follow date,
  opportunity text,
  problem text,
  recommendation text,
  budget text,
  notes text,
  message text,
  contacts jsonb default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.prospects enable row level security;
create policy "Users can read their prospects" on public.prospects for select using (auth.uid() = owner_id);
create policy "Users can create their prospects" on public.prospects for insert with check (auth.uid() = owner_id);
create policy "Users can update their prospects" on public.prospects for update using (auth.uid() = owner_id);
create policy "Users can delete their prospects" on public.prospects for delete using (auth.uid() = owner_id);
