import http from 'node:http';

const env = process.env;
const port = Number(env.PORT || 8787);
const origin = env.ALLOWED_ORIGIN || '*';
const json = (res, status, body) => { res.writeHead(status, {'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-headers':'content-type, authorization'}); res.end(JSON.stringify(body)); };
const readBody = req => new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}});req.on('error',reject)});
function requireConfig(){for(const k of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','OPENROUTER_API_KEY']) if(!env[k]) throw new Error(`Missing server configuration: ${k}`);}
async function supabase(path, options={}){requireConfig();const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(options.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(`Database request failed (${r.status}): ${text.slice(0,300)}`);return text?JSON.parse(text):null;}
async function agent(body){requireConfig();const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'content-type':'application/json','HTTP-Referer':'https://buzzent.app','X-Title':'BUZZENT Agent'},body:JSON.stringify({model:env.OPENROUTER_MODEL||'openai/gpt-4o-mini',messages:body.messages||[],tools:body.tools||[],tool_choice:body.tool_choice||'auto'})});if(!r.ok)throw new Error('AI provider request failed');return r.json();}
function webhookTokenMatches(received){return Boolean(env.META_VERIFY_TOKEN&&received===env.META_VERIFY_TOKEN);}
async function findOrCreateCustomer(businessId,phone,name){const existing=await supabase(`customers?business_id=eq.${encodeURIComponent(businessId)}&phone=eq.${encodeURIComponent(phone)}&select=id,name,phone&limit=1`);if(existing?.[0]){await supabase(`customers?id=eq.${existing[0].id}`,{method:'PATCH',body:JSON.stringify({name:name||existing[0].name,last_interaction:new Date().toISOString(),channel:'WHATSAPP'})});return existing[0];}const created=await supabase('customers',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({business_id:businessId,name:name||phone,phone,channel:'WHATSAPP',last_interaction:new Date().toISOString()})});return created?.[0];}
async function findOrCreateConversation(businessId,customerId){const existing=await supabase(`conversations?business_id=eq.${encodeURIComponent(businessId)}&customer_id=eq.${encodeURIComponent(customerId)}&channel=eq.WHATSAPP&status=neq.CLOSED&select=id,status&limit=1`);if(existing?.[0])return existing[0];const created=await supabase('conversations',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({business_id:businessId,customer_id:customerId,channel:'WHATSAPP',status:'AGENT_ACTIVE',last_message_at:new Date().toISOString()})});return created?.[0];}
async function saveMessage(conversationId,role,content){await supabase('messages',{method:'POST',body:JSON.stringify({conversation_id:conversationId,role,content})});await supabase(`conversations?id=eq.${encodeURIComponent(conversationId)}`,{method:'PATCH',body:JSON.stringify({last_message_at:new Date().toISOString()})});}
async function sendWhatsAppMessage(phoneNumberId,accessToken,recipient,text){const version=env.META_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${version}/${encodeURIComponent(phoneNumberId)}/messages`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:recipient,type:'text',text:{preview_url:false,body:text}})});if(!r.ok)throw new Error(`Meta send failed (${r.status})`);return r.json();}
async function processWhatsAppWebhook(payload){for(const entry of payload?.entry||[]){for(const change of entry.changes||[]){const value=change.value||{};for(const incoming of value.messages||[]){if(incoming.type!=='text'||!incoming.text?.body||!value.metadata?.phone_number_id)continue;const phoneNumberId=value.metadata.phone_number_id;const connections=await supabase(`integration_connections?channel=eq.WHATSAPP&external_id=eq.${encodeURIComponent(phoneNumberId)}&active=eq.true&select=business_id,external_id,access_token&limit=1`);const connection=connections?.[0];if(!connection){console.warn(`No BUZZENT connection for WhatsApp phone ${phoneNumberId}`);continue;}const contact=(value.contacts||[]).find(item=>item.wa_id===incoming.from);const customer=await findOrCreateCustomer(connection.business_id,incoming.from,contact?.profile?.name);const conversation=await findOrCreateConversation(connection.business_id,customer.id);await saveMessage(conversation.id,'CLIENTE',incoming.text.body);const completion=await agent({messages:[{role:'system',content:'Sos el agente de BUZZENT. Respondé en español, de forma clara y breve. No inventes horarios ni confirmes una reserva sin datos reales.'},{role:'user',content:incoming.text.body}]});const answer=completion?.choices?.[0]?.message?.content;if(!answer)continue;await sendWhatsAppMessage(connection.external_id,connection.access_token,incoming.from,answer);await saveMessage(conversation.id,'AGENTE',answer);}}}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type, authorization'});return res.end()}try{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,service:'buzzent-backend'});if(req.method==='GET'&&(url.pathname==='/v1/meta/webhook'||url.pathname==='/v1/meta/whatsapp/webhook')){const mode=url.searchParams.get('hub.mode'),token=url.searchParams.get('hub.verify_token'),challenge=url.searchParams.get('hub.challenge');if(mode==='subscribe'&&webhookTokenMatches(token)){res.writeHead(200,{'content-type':'text/plain; charset=utf-8'});return res.end(challenge||'')}return json(res,403,{error:'Webhook verification failed'});}if(req.method==='POST'&&(url.pathname==='/v1/meta/webhook'||url.pathname==='/v1/meta/whatsapp/webhook')){const payload=await readBody(req);res.statusCode=200;res.setHeader('content-type','application/json; charset=utf-8');res.end(JSON.stringify({received:true}));processWhatsAppWebhook(payload).catch(error=>console.error(`WhatsApp webhook: ${error.message}`));return;}if(req.method==='POST'&&url.pathname==='/v1/agent/respond')return json(res,200,await agent(await readBody(req)));if(req.method==='GET'&&url.pathname==='/v1/services')return json(res,200,await supabase(`services?business_id=eq.${encodeURIComponent(url.searchParams.get('business_id')||'')}&active=eq.true&select=*`));if(req.method==='POST'&&url.pathname==='/v1/appointments'){const b=await readBody(req);if(!b.business_id||!b.starts_at||!b.ends_at||!b.service_id)return json(res,400,{error:'Missing appointment data'});const clashes=await supabase(`appointments?business_id=eq.${encodeURIComponent(b.business_id)}&status=not.in.(CANCELADO,RECHAZADO)&starts_at=lt.${encodeURIComponent(b.ends_at)}&ends_at=gt.${encodeURIComponent(b.starts_at)}&select=id`);if(clashes?.length)return json(res,409,{error:'Horario ocupado'});return json(res,201,(await supabase('appointments',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify(b)}))?.[0]);}return json(res,404,{error:'Not found'});}catch(e){console.error(e.message);return json(res,500,{error:'No pudimos completar esta acción'});}});
server.listen(port,()=>console.log(`BUZZENT backend listening on ${port}`));
