import http from 'node:http';

const env = process.env;
const port = Number(env.PORT || 8787);
const json = (res, status, body) => { res.writeHead(status, {'content-type':'application/json; charset=utf-8','access-control-allow-origin':env.ALLOWED_ORIGIN||'*','access-control-allow-headers':'content-type, authorization'}); res.end(JSON.stringify(body)); };
const readBody = req => new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}});req.on('error',reject)});
function requireConfig(){for(const k of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','OPENROUTER_API_KEY']) if(!env[k]) throw new Error(`Missing server configuration: ${k}`);}
async function supabase(path, options={}){requireConfig();const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'content-type':'application/json',...(options.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(`Database request failed (${r.status})`);return text?JSON.parse(text):null;}
async function agent(body){requireConfig();const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${env.OPENROUTER_API_KEY}`,'content-type':'application/json','HTTP-Referer':'https://buzzent.app','X-Title':'BUZZENT Agent'},body:JSON.stringify({model:env.OPENROUTER_MODEL||'openai/gpt-4o-mini',messages:body.messages||[],tools:body.tools||[],tool_choice:body.tool_choice||'auto'})});if(!r.ok)throw new Error('AI provider request failed');return r.json();}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':env.ALLOWED_ORIGIN||'*','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type, authorization'});return res.end()}try{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&url.pathname==='/health')return json(res,200,{ok:true,service:'buzzent-backend'});if(req.method==='POST'&&url.pathname==='/v1/agent/respond')return json(res,200,await agent(await readBody(req)));if(req.method==='GET'&&url.pathname==='/v1/services')return json(res,200,await supabase(`services?business_id=eq.${url.searchParams.get('business_id')}&active=eq.true&select=*`));if(req.method==='POST'&&url.pathname==='/v1/appointments'){const b=await readBody(req);if(!b.business_id||!b.starts_at||!b.ends_at||!b.service_id)return json(res,400,{error:'Missing appointment data'});const clashes=await supabase(`appointments?business_id=eq.${b.business_id}&status=not.in.(CANCELADO,RECHAZADO)&starts_at=lt.${encodeURIComponent(b.ends_at)}&ends_at=gt.${encodeURIComponent(b.starts_at)}&select=id`);if(clashes?.length)return json(res,409,{error:'Horario ocupado'});return json(res,201,(await supabase('appointments',{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify(b)}))?.[0]);}return json(res,404,{error:'Not found'});}catch(e){console.error(e.message);return json(res,500,{error:'No pudimos completar esta acción'});}});
server.listen(port,()=>console.log(`BUZZENT backend listening on ${port}`));
