-- Buzzent Agent Operations: migración no destructiva.
-- Ejecutar después de supabase/schema.sql desde Supabase SQL Editor.

alter table public.prospects
  add column if not exists commercial_status text,
  add column if not exists agent_enabled boolean not null default false,
  add column if not exists handoff_reason text,
  add column if not exists research jsonb not null default '[]'::jsonb,
  add column if not exists digital_presence jsonb not null default '{}'::jsonb,
  add column if not exists sale_data jsonb not null default '{}'::jsonb;

update public.prospects
set commercial_status = case
  when status = 'Pendiente' then 'NEW'
  when status = 'Contactado' then 'CONTACTED'
  when status in ('Respondió','Interesado') then 'INTERESTED'
  when status in ('Propuesta enviada','Negociación') then 'PROPOSAL'
  when status = 'Cliente' then 'WON'
  when status in ('No interesado','Descartado','No responde') then 'LOST'
  else 'NEW'
end
where commercial_status is null;

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint not null references public.prospects(id) on delete cascade,
  channel text not null default 'DEMO',
  status text not null default 'ACTIVE',
  agent_enabled boolean not null default false,
  unread_count integer not null default 0,
  last_message_at timestamptz,
  handoff_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, prospect_id, channel)
);

create table if not exists public.conversation_messages (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  direction text not null check (direction in ('INBOUND','OUTBOUND')),
  sender text not null check (sender in ('PROSPECT','BUZZENT','HUMAN')),
  content text not null,
  channel text not null default 'DEMO',
  delivery_status text not null default 'SIMULATED',
  is_ai boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.commercial_settings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade unique,
  company_name text not null default 'Buzzent',
  description text not null default 'Web · Tecnología · Diseño',
  slogan text not null default 'Soluciones digitales que impulsan tu negocio',
  services jsonb not null default '[]'::jsonb,
  pricing jsonb not null default '{"starting_price":"$30.000","deposit":"$16.000","term":"aproximadamente 1 semana","domain":".com.ar según el paquete contratado"}'::jsonb,
  agent_rules jsonb not null default '{"demo_mode":true,"max_new_contacts_per_day":10,"max_followups_per_day":20,"min_interval_minutes":30,"allowed_hours":"09:00-18:00"}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_actions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint references public.prospects(id) on delete set null,
  action_type text not null,
  mode text not null default 'DEMO' check (mode in ('DEMO','REAL')),
  payload jsonb not null default '{}'::jsonb,
  result text not null default 'SIMULATED',
  created_at timestamptz not null default now()
);

create table if not exists public.agent_notifications (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint references public.prospects(id) on delete set null,
  kind text not null,
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.conversations enable row level security;
alter table public.conversation_messages enable row level security;
alter table public.commercial_settings enable row level security;
alter table public.agent_actions enable row level security;
alter table public.agent_notifications enable row level security;

drop policy if exists "Users can manage their conversations" on public.conversations;
create policy "Users can manage their conversations" on public.conversations for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users can manage their conversation messages" on public.conversation_messages;
create policy "Users can manage their conversation messages" on public.conversation_messages for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users can manage their commercial settings" on public.commercial_settings;
create policy "Users can manage their commercial settings" on public.commercial_settings for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users can manage their agent actions" on public.agent_actions;
create policy "Users can manage their agent actions" on public.agent_actions for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users can manage their agent notifications" on public.agent_notifications;
create policy "Users can manage their agent notifications" on public.agent_notifications for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
