-- Automatización real de outreach por email. Se ejecuta sólo cuando
-- commercial_settings.agent_rules.automation_enabled = true.
alter table public.prospects
  add column if not exists last_contacted_at timestamptz;

create table if not exists public.outreach_messages (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint not null references public.prospects(id) on delete cascade,
  run_date date not null default (timezone('America/Argentina/Buenos_Aires', now()))::date,
  channel text not null default 'EMAIL',
  status text not null default 'CLAIMED' check (status in ('CLAIMED','SENT','FAILED','SKIPPED')),
  subject text not null,
  body text not null,
  provider_id text,
  error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(owner_id, prospect_id, run_date)
);

alter table public.outreach_messages enable row level security;
drop policy if exists "Users can read their outreach messages" on public.outreach_messages;
create policy "Users can read their outreach messages" on public.outreach_messages
  for select using (auth.uid() = owner_id);

create index if not exists outreach_messages_daily_owner_idx
  on public.outreach_messages(owner_id, run_date, status);

-- El job llama a la Edge Function con una clave interna; la función valida
-- esta clave antes de consultar o modificar datos de cualquier usuario.
create extension if not exists pg_cron;
create extension if not exists pg_net;

