create table if not exists public.research_sources (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint not null references public.prospects(id) on delete cascade,
  source_type text not null default 'PUBLIC_WEB',
  source_url text,
  title text,
  finding text not null,
  opportunity text,
  verified boolean not null default false,
  researched_at timestamptz not null default now()
);

create table if not exists public.prospect_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  prospect_id bigint references public.prospects(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.research_sources enable row level security;
alter table public.prospect_events enable row level security;
drop policy if exists "Users can manage their research sources" on public.research_sources;
create policy "Users can manage their research sources" on public.research_sources for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users can manage their prospect events" on public.prospect_events;
create policy "Users can manage their prospect events" on public.prospect_events for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create index if not exists research_sources_prospect_idx on public.research_sources (prospect_id, researched_at desc);
create index if not exists prospect_events_owner_idx on public.prospect_events (owner_id, created_at desc);
