create table if not exists public.integrations (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  channel text not null,
  status text not null default 'DISCONNECTED',
  config jsonb not null default '{}'::jsonb,
  last_error text,
  connected_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(owner_id, provider, channel)
);

alter table public.integrations enable row level security;
drop policy if exists "Users can manage their integrations" on public.integrations;
create policy "Users can manage their integrations" on public.integrations for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
